version: "3.8"

services:
  frontend:
    image: $ECR_REPO:frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    image: $ECR_REPO:backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - NODE_ENV=production
